apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datetime-app
  template:
    metadata:
      labels:
        app: datetime-app
    spec:
      containers:
      - name: datetime-app
        image: reganx17/datetime-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: datetime-app-service
spec:
  type: LoadBalancer
  selector:
    app: datetime-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
